Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Load Dataset

In [2]:
df = pd.read_csv("marketing_campaign_dataset.csv")
df.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,"$16,174.00",6.29,Chicago,Spanish,506.0,1922.0,6.0,Health & Wellness,2021-01-01
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,"$11,566.00",5.61,New York,German,116.0,7523.0,7.0,Fashionistas,2021-01-02
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,"$10,200.00",7.18,Los Angeles,French,584.0,7698.0,1.0,Outdoor Adventurers,2021-01-03
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,"$12,724.00",5.55,Miami,Mandarin,217.0,1820.0,7.0,Health & Wellness,2021-01-04
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,"$16,452.00",6.50,Los Angeles,Mandarin,379.0,4201.0,3.0,Health & Wellness,2021-01-05

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69669 entries, 0 to 69668
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       69669 non-null  int64
 1   Company           69669 non-null  object
 2   Campaign_Type     69669 non-null  object
 3   Target_Audience   69669 non-null  object
 4   Duration          69669 non-null  object
 5   Channel_Used      69669 non-null  object
 6   Conversion_Rate   69669 non-null  float64
 7   Acquisition_Cost  69669 non-null  object
 8   ROI               69669 non-null  float64
 9   Location          69668 non-null  object
 10  Language          69668 non-null  object
 11  Clicks            69668 non-null  float64
 12  Impressions       69668 non-null  float64
 13  Engagement_Score  69668 non-null  float64
 14  Customer_Segment  69668 non-null  object
 15  Date              69668 non-null  object
dtypes: float64(5), int64(1), object(10)
memory usage: 8.5+ MB

In [4]:
#Change Data Type for Acquisition_Cost and #Date
df['Acquisition_Cost'] = df['Acquisition_Cost'].replace('[\$,]', '', regex=True).astype(float)
df['Date'] = pd.to_datetime(df['Date'])

<>:2: SyntaxWarning: invalid escape sequence '\$'
<>:2: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipykernel_317/1348025521.py:2: SyntaxWarning: invalid escape sequence '\$'
  df['Acquisition_Cost'] = df['Acquisition_Cost'].replace('[\$,]', '', regex=True).astype(float)

In [5]:
#Recheck data information again
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69669 entries, 0 to 69668
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       69669 non-null  int64
 1   Company           69669 non-null  object
 2   Campaign_Type     69669 non-null  object
 3   Target_Audience   69669 non-null  object
 4   Duration          69669 non-null  object
 5   Channel_Used      69669 non-null  object
 6   Conversion_Rate   69669 non-null  float64
 7   Acquisition_Cost  69669 non-null  float64
 8   ROI               69669 non-null  float64
 9   Location          69668 non-null  object
 10  Language          69668 non-null  object
 11  Clicks            69668 non-null  float64
 12  Impressions       69668 non-null  float64
 13  Engagement_Score  69668 non-null  float64
 14  Customer_Segment  69668 non-null  object
 15  Date              69668 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(6), int64(1), object(8)
memory usage: 8.5+ MB

In [6]:
df.describe()

,Campaign_ID,Conversion_Rate,Acquisition_Cost,ROI,Clicks,Impressions,Engagement_Score,Date
count,69669.000000,69669.000000,69669.000000,69669.000000,69668.000000,69668.000000,69668.000000,69668
mean,34835.000000,0.080102,12507.366016,5.006591,549.327539,5504.091836,5.493311,2021-07-01 21:25:32.227134464
min,1.000000,0.010000,5000.000000,2.000000,100.000000,1000.000000,1.000000,2021-01-01 00:00:00
25%,17418.000000,0.040000,8759.000000,3.510000,324.000000,3272.000000,3.000000,2021-04-02 00:00:00
50%,34835.000000,0.080000,12500.000000,5.010000,549.000000,5514.000000,5.000000,2021-07-02 00:00:00
75%,52252.000000,0.120000,16250.000000,6.510000,775.000000,7747.000000,8.000000,2021-10-01 00:00:00
max,69669.000000,0.150000,20000.000000,8.000000,1000.000000,10000.000000,10.000000,2021-12-31 00:00:00
std,20111.852289,0.040609,4338.991528,1.735174,259.945165,2593.459739,2.871444,NaN

Data Preprocessing and Cleaning

In [7]:
#check for missing value
df.isnull().sum()

Campaign_ID         0
Company             0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Conversion_Rate     0
Acquisition_Cost    0
ROI                 0
Location            1
Language            1
Clicks              1
Impressions         1
Engagement_Score    1
Customer_Segment    1
Date                1
dtype: int64

In [8]:
#Check for duplicates
df.duplicated().sum()

np.int64(0)

In [9]:
#Creating Month Column
df['Month'] = df['Date'].dt.month

In [10]:
df.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,Language,Clicks,Impressions,Engagement_Score,Customer_Segment,Date,Month
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,16174.0,6.29,Chicago,Spanish,506.0,1922.0,6.0,Health & Wellness,2021-01-01,1.0
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,11566.0,5.61,New York,German,116.0,7523.0,7.0,Fashionistas,2021-01-02,1.0
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,10200.0,7.18,Los Angeles,French,584.0,7698.0,1.0,Outdoor Adventurers,2021-01-03,1.0
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,12724.0,5.55,Miami,Mandarin,217.0,1820.0,7.0,Health & Wellness,2021-01-04,1.0
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,16452.0,6.50,Los Angeles,Mandarin,379.0,4201.0,3.0,Health & Wellness,2021-01-05,1.0

#KPI Calculations

In [11]:
#Click Through Rate
df["CTR"] = df["Clicks"] / df["Impressions"]

In [12]:
#Number of Conversions
df["Conversions"] = df["Clicks"] * df["Conversion_Rate"]

In [13]:
#Revenue
df["Revenue"] = df["Acquisition_Cost"] * (1 + df["ROI"])

In [14]:
#Calculate Return on Ad Spend
df["ROAS"] = df["Revenue"] / df["Acquisition_Cost"]

In [15]:
df.head()

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,...,Clicks,Impressions,Engagement_Score,Customer_Segment,Date,Month,CTR,Conversions,Revenue,ROAS
0,1,Innovate Industries,Email,Men 18-24,30 days,Google Ads,0.04,16174.0,6.29,Chicago,...,506.0,1922.0,6.0,Health & Wellness,2021-01-01,1.0,0.263267,20.24,117908.46,7.29
1,2,NexGen Systems,Email,Women 35-44,60 days,Google Ads,0.12,11566.0,5.61,New York,...,116.0,7523.0,7.0,Fashionistas,2021-01-02,1.0,0.015419,13.92,76451.26,6.61
2,3,Alpha Innovations,Influencer,Men 25-34,30 days,YouTube,0.07,10200.0,7.18,Los Angeles,...,584.0,7698.0,1.0,Outdoor Adventurers,2021-01-03,1.0,0.075864,40.88,83436.00,8.18
3,4,DataTech Solutions,Display,All Ages,60 days,YouTube,0.11,12724.0,5.55,Miami,...,217.0,1820.0,7.0,Health & Wellness,2021-01-04,1.0,0.119231,23.87,83342.20,6.55
4,5,NexGen Systems,Email,Men 25-34,15 days,YouTube,0.05,16452.0,6.50,Los Angeles,...,379.0,4201.0,3.0,Health & Wellness,2021-01-05,1.0,0.090217,18.95,123390.00,7.50

#Exploratory Data Analysis (EDA)

In [16]:
#Channel Performance
df.groupby("Channel_Used")[["Revenue","Acquisition_Cost"]].sum()

                   Revenue  Acquisition_Cost
Channel_Used
Email         8.819240e+08       146363556.0
Facebook      8.642181e+08       143656950.0
Google Ads    8.696997e+08       144713061.0
Instagram     8.755631e+08       146458557.0
Website       8.736293e+08       145508409.0
YouTube       8.689832e+08       144675150.0

In [17]:
# ROI by Channel
df.groupby("Channel_Used")["ROI"].mean().sort_values(ascending=False)

Channel_Used
Email         5.025543
Google Ads    5.013567
Website       5.012495
Facebook      5.007388
YouTube       5.002781
Instagram     4.977905
Name: ROI, dtype: float64

In [18]:
#Conversion Rate by Channel
df.groupby("Channel_Used")["Conversion_Rate"].mean()

Channel_Used
Email         0.080177
Facebook      0.079871
Google Ads    0.080524
Instagram     0.079855
Website       0.080341
YouTube       0.079844
Name: Conversion_Rate, dtype: float64

In [19]:
# Top Performing Campaigns
df.sort_values("ROI", ascending=False).head(10)

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,...,Clicks,Impressions,Engagement_Score,Customer_Segment,Date,Month,CTR,Conversions,Revenue,ROAS
29549,29550,NexGen Systems,Display,Women 25-34,30 days,Facebook,0.14,6854.0,8.0,Miami,...,183.0,1765.0,4.0,Foodies,2021-12-16,12.0,0.103683,25.62,61686.0,9.0
3231,3232,Alpha Innovations,Display,Women 25-34,30 days,Instagram,0.01,12759.0,8.0,New York,...,476.0,3627.0,6.0,Tech Enthusiasts,2021-11-08,11.0,0.131238,4.76,114831.0,9.0
20015,20016,Innovate Industries,Influencer,Women 25-34,45 days,Email,0.03,12130.0,8.0,Houston,...,934.0,5075.0,5.0,Foodies,2021-11-02,11.0,0.184039,28.02,109170.0,9.0
29081,29082,Innovate Industries,Email,Men 25-34,45 days,Facebook,0.06,9611.0,8.0,Los Angeles,...,279.0,1910.0,5.0,Fashionistas,2021-09-04,9.0,0.146073,16.74,86499.0,9.0
16537,16538,Innovate Industries,Email,All Ages,45 days,YouTube,0.01,12085.0,8.0,Chicago,...,568.0,5640.0,10.0,Health & Wellness,2021-04-23,4.0,0.100709,5.68,108765.0,9.0
47112,47113,DataTech Solutions,Influencer,Men 25-34,15 days,Google Ads,0.12,17969.0,8.0,Chicago,...,164.0,3288.0,3.0,Tech Enthusiasts,2021-01-28,1.0,0.049878,19.68,161721.0,9.0
44575,44576,TechCorp,Display,Men 25-34,45 days,Email,0.10,12845.0,8.0,Los Angeles,...,996.0,9398.0,9.0,Foodies,2021-02-15,2.0,0.105980,99.60,115605.0,9.0
67606,67607,Innovate Industries,Influencer,Men 18-24,15 days,Facebook,0.07,11172.0,8.0,Miami,...,136.0,3930.0,8.0,Health & Wellness,2021-03-23,3.0,0.034606,9.52,100548.0,9.0
64343,64344,Innovate Industries,Influencer,All Ages,30 days,YouTube,0.11,12094.0,8.0,Houston,...,319.0,5664.0,7.0,Tech Enthusiasts,2021-04-14,4.0,0.056321,35.09,108846.0,9.0
15651,15652,DataTech Solutions,Display,All Ages,15 days,Website,0.03,12708.0,8.0,Los Angeles,...,358.0,8767.0,7.0,Outdoor Adventurers,2021-11-18,11.0,0.040835,10.74,114372.0,9.0

In [20]:
# Worst Campaigns
df.sort_values("ROI").head(10)

,Campaign_ID,Company,Campaign_Type,Target_Audience,Duration,Channel_Used,Conversion_Rate,Acquisition_Cost,ROI,Location,...,Clicks,Impressions,Engagement_Score,Customer_Segment,Date,Month,CTR,Conversions,Revenue,ROAS
57914,57915,TechCorp,Search,Men 25-34,45 days,YouTube,0.03,19404.0,2.0,Miami,...,379.0,5107.0,8.0,Foodies,2021-09-02,9.0,0.074212,11.37,58212.0,3.0
32615,32616,TechCorp,Email,Women 25-34,15 days,Website,0.12,7038.0,2.0,Chicago,...,819.0,9994.0,7.0,Health & Wellness,2021-05-11,5.0,0.081949,98.28,21114.0,3.0
68622,68623,NexGen Systems,Display,Women 25-34,15 days,Instagram,0.04,11071.0,2.0,Chicago,...,665.0,6692.0,1.0,Fashionistas,2021-01-03,1.0,0.099372,26.60,33213.0,3.0
57347,57348,TechCorp,Search,Women 25-34,30 days,Email,0.12,7562.0,2.0,Miami,...,163.0,2279.0,5.0,Tech Enthusiasts,2021-02-12,2.0,0.071523,19.56,22686.0,3.0
40004,40005,TechCorp,Influencer,Men 18-24,60 days,Facebook,0.05,19356.0,2.0,Houston,...,542.0,5678.0,4.0,Health & Wellness,2021-08-08,8.0,0.095456,27.10,58068.0,3.0
15476,15477,NexGen Systems,Influencer,Men 18-24,60 days,Email,0.09,6340.0,2.0,Houston,...,720.0,5019.0,1.0,Health & Wellness,2021-05-27,5.0,0.143455,64.80,19020.0,3.0
60544,60545,TechCorp,Influencer,All Ages,30 days,Facebook,0.06,18896.0,2.0,Miami,...,406.0,4902.0,5.0,Health & Wellness,2021-11-16,11.0,0.082823,24.36,56688.0,3.0
23051,23052,Innovate Industries,Email,All Ages,15 days,Facebook,0.02,9003.0,2.0,Los Angeles,...,931.0,6462.0,1.0,Health & Wellness,2021-02-26,2.0,0.144073,18.62,27009.0,3.0
10285,10286,Alpha Innovations,Email,All Ages,15 days,Facebook,0.03,18589.0,2.0,New York,...,809.0,9730.0,6.0,Tech Enthusiasts,2021-03-07,3.0,0.083145,24.27,55767.0,3.0
7823,7824,TechCorp,Social Media,Women 25-34,60 days,Google Ads,0.15,17374.0,2.0,Los Angeles,...,349.0,7695.0,10.0,Outdoor Adventurers,2021-06-08,6.0,0.045354,52.35,52122.0,3.0

#Export Clean Dataset

In [21]:
df.to_csv("marketing_campaign_cleaned.csv", index=False)